- include_vars:
    file: "../../vars/main.yml"

- name: Add .bash_profile
  copy:
    src: ../files/.bash_profile
    dest: "{{ bash_profile_path }}"

- name: Add .bash_aliases
  copy:
    src: ../files/.bash_aliases
    dest: "{{ bash_aliases_path }}"

- name: Load .bash_profile in .bashrc
  blockinfile:
    path: "{{ bashrc_path }}"
    block: |
      if [ -f {{ bash_profile_path }} ]; then
        . {{ bash_profile_path }}
      fi

- name: Create custom bin dir
  file:
    path: "{{ custom_bin_dir }}"
    state: directory

- name: Add custom bin dir to $PATH
  lineinfile:
    line: "export PATH=$PATH:{{ custom_bin_dir }}"
    path: "{{ bash_profile_path }}"
    state: present
