- name: Add the official KeePassXC repository
  apt_repository:
    repo: ppa:phoerious/keepassxc
    state: present
  become: true

- name: Install KeePassXC
  apt:
    name: keepassxc
  become: true
