- include_vars:
    file: "../../vars/main.yml"

- name: Check if should install Wine
  shell: which wine || echo true
  register: should_install_wine

- name: Add Wine key
  apt_key:
    url: "{{ wine_dl_url }}"
    state: present
  become: true
  when: should_install_wine.stdout == 'true'

- name: Add Wine repository
  shell: "apt-add-repository {{ wine_ubuntu_repository }}"
  become: true
  when: should_install_wine.stdout == 'true'

- name: Install Wine
  apt:
    name: winehq-stable
    update_cache: true
  become: true
  when: should_install_wine.stdout == 'true'

- name: Check if should download Winetricks
  shell:
    cmd: "(source {{ bash_profile_path }} && which winetricks) || echo true"
    executable: /bin/bash
  register: should_download_winetricks

- name: Download Winetricks
  get_url:
    url: "{{ winetricks_dl_url }}"
    dest: "{{ winetricks_path }}"
    mode: 0744
  when: should_download_winetricks.stdout == 'true'

- name: Install cabextract
  apt:
    name: cabextract
    state: present

- name: Check if should install .NET Framework 4.5.2
  shell:
    cmd: "(source {{ bash_profile_path }} && winetricks list-installed | grep dotnet452) || echo true"
    executable: /bin/bash
  register: should_install_dotnet452

- name: Install .NET Framework 4.5.2
  shell:
    cmd: "source {{ bash_profile_path }} && winetricks dotnet452"
    executable: /bin/bash
  when: should_install_dotnet452.stdout == 'true'

- name: Check if should install corefonts
  shell:
    cmd: "(source {{ bash_profile_path }} && winetricks list-installed | grep corefonts) || echo true"
    executable: /bin/bash
  register: should_install_corefonts

- name: Install corefonts
  shell:
    cmd: "source {{ bash_profile_path }} && winetricks corefonts"
    executable: /bin/bash
  when: should_install_dotnet452 == 'true'
