- name: Check if should install Sublime Text
  shell: which subl || echo true
  register: should_isntall_sublime

- name: Prepare for Sublime Text installation
  shell: wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -
  become: true
  when: should_isntall_sublime.stdout == 'true'

- name: Set Sublime Text stable channel
  shell: echo "deb https://download.sublimetext.com/ apt/stable/" | tee /etc/apt/sources.list.d/sublime-text.list
  become: true
  when: should_isntall_sublime.stdout == 'true'

- name: Install Sublime Text
  apt:
    name: sublime-text
    update_cache: true
  become: true
  when: should_isntall_sublime.stdout == 'true'
